const jobTitles = [ 
  { value: 'Data Science Manager', label: 'Data Science Manager' },
  { value: 'Data Engineer', label: 'Data Engineer' },
  { value: 'Analytics Engineer', label: 'Analytics Engineer' },
  { value: 'Machine Learning Developer',
    label: 'Machine Learning Developer' },
  { value: 'Data Engineering Manager',
    label: 'Data Engineering Manager' },
  { value: 'Data Scientist', label: 'Data Scientist' },
  { value: 'Data Operations Engineer',
    label: 'Data Operations Engineer' },
  { value: 'Data Analyst', label: 'Data Analyst' },
  { value: 'ETL Developer', label: 'ETL Developer' },
  { value: 'Data Manager', label: 'Data Manager' },
  { value: 'Director of Data Science',
    label: 'Director of Data Science' },
  { value: 'Applied Scientist', label: 'Applied Scientist' },
  { value: 'Financial Data Analyst',
    label: 'Financial Data Analyst' },
  { value: 'Data Operations Analyst',
    label: 'Data Operations Analyst' },
  { value: 'Machine Learning Scientist',
    label: 'Machine Learning Scientist' },
  { value: 'AI Scientist', label: 'AI Scientist' },
  { value: 'Computer Vision Software Engineer',
    label: 'Computer Vision Software Engineer' },
  { value: 'Data Specialist', label: 'Data Specialist' },
  { value: 'Applied Machine Learning Scientist',
    label: 'Applied Machine Learning Scientist' },
  { value: 'Data Analytics Consultant',
    label: 'Data Analytics Consultant' },
  { value: 'Product Data Analyst', label: 'Product Data Analyst' },
  { value: 'BI Data Analyst', label: 'BI Data Analyst' },
  { value: '3D Computer Vision Researcher',
    label: '3D Computer Vision Researcher' },
  { value: 'Lead Data Scientist', label: 'Lead Data Scientist' },
  { value: 'Research Scientist', label: 'Research Scientist' },
  { value: 'Machine Learning Infrastructure Engineer',
    label: 'Machine Learning Infrastructure Engineer' },
  { value: 'Lead Machine Learning Engineer',
    label: 'Lead Machine Learning Engineer' },
  { value: 'Machine Learning Engineer',
    label: 'Machine Learning Engineer' },
  { value: 'Data Architect', label: 'Data Architect' },
  { value: 'Machine Learning Research Engineer',
    label: 'Machine Learning Research Engineer' },
  { value: 'Applied Data Scientist',
    label: 'Applied Data Scientist' },
  { value: 'Cloud Data Architect', label: 'Cloud Data Architect' },
  { value: 'Machine Learning Manager',
    label: 'Machine Learning Manager' },
  { value: 'Business Data Analyst',
    label: 'Business Data Analyst' },
  { value: 'ML Engineer', label: 'ML Engineer' },
  { value: 'Data Analytics Manager',
    label: 'Data Analytics Manager' },
  { value: 'Lead Data Engineer', label: 'Lead Data Engineer' },
  { value: 'Head of Machine Learning',
    label: 'Head of Machine Learning' },
  { value: 'Data Science Engineer',
    label: 'Data Science Engineer' },
  { value: 'Head of Data Science', label: 'Head of Data Science' },
{ value: 'NLP Engineer', label: 'NLP Engineer' },
  { value: 'Computer Vision Engineer',
    label: 'Computer Vision Engineer' },
  { value: 'Head of Data', label: 'Head of Data' },
  { value: 'Principal Data Analyst',
    label: 'Principal Data Analyst' },
  { value: 'Data Analytics Lead', label: 'Data Analytics Lead' },
  { value: 'Data Analytics Engineer',
    label: 'Data Analytics Engineer' },
  { value: 'Principal Data Scientist',
    label: 'Principal Data Scientist' },
  { value: 'Principal Data Engineer',
    label: 'Principal Data Engineer' },
  { value: 'Big Data Engineer', label: 'Big Data Engineer' },
  { value: 'Data Science Consultant',
    label: 'Data Science Consultant' },
  { value: 'Lead Data Analyst', label: 'Lead Data Analyst' },
  { value: 'Marketing Data Analyst',
    label: 'Marketing Data Analyst' },
  { value: 'Director of Data Engineering',
    label: 'Director of Data Engineering' },
  { value: 'Cloud Data Engineer', label: 'Cloud Data Engineer' },
  { value: 'Big Data Architect', label: 'Big Data Architect' },
  { value: 'Staff Data Scientist', label: 'Staff Data Scientist' },
  { value: 'Finance Data Analyst', label: 'Finance Data Analyst' } 
]

export default jobTitles;