const jobLocation = [
    { value: 'US', label: 'United States of America' },
{ value: 'TH', label: 'Thailand' },
{ value: 'BR', label: 'Brazil' },
{ value: 'FR', label: 'France' },
{ value: 'GB', label: 'The United Kingdom' },
{ value: 'NL', label: 'Netherlands' },
{ value: 'DE', label: 'Germany' },
{ value: 'IN', label: 'India' },
{ value: 'GR', label: 'Greece' },
{ value: 'ES', label: 'Spain' },
{ value: 'DK', label: 'Denmark' },
{ value: 'BO', label: 'Bolivia' },
{ value: 'PH', label: 'Philippines' },
{ value: 'AU', label: 'Australia' },
{ value: 'AL', label: 'Albania' },
{ value: 'PT', label: 'Portugal' },
{ value: 'CA', label: 'Canada' },
{ value: 'PR', label: 'Puerto Rico' },
{ value: 'AR', label: 'Argentina' },
{ value: 'BE', label: 'Belgium' },
{ value: 'ID', label: 'Indonesia' },
{ value: 'AR', label: 'Austria' },
{ value: 'AX', label: 'Aland Islands' },
{ value: 'AR', label: 'Cuba' },
{ value: 'TR', label: 'Turkiye' },
{ value: 'SG', label: 'Singapore' },
{ value: 'EG', label: 'Egypt' },
{ value: 'IT', label: 'Italy' },
{ value: 'MX', label: 'Mexico' },
{ value: 'AE', label: 'United Arab Emirates' },
{ value: 'IE', label: 'Ireland' },
{ value: 'LU', label: 'Luxembourg' },
{ value: 'SI', label: 'Slovenia' },
{ value: 'MY', label: 'Malaysia' },
{ value: 'EE', label: 'Estonia' },
{ value: 'PL', label: 'Poland' },
{ value: 'HN', label: 'Honduras' },
{ value: 'CZ', label: 'Czechia' },
{ value: 'CH', label: 'Switzerland' },
{ value: 'PK', label: 'Pakistan' },
{ value: 'JP', label: 'Japan' },
{ value: 'DZ', label: 'Algeria' },
{ value: 'RO', label: 'Romania' },
{ value: 'IQ', label: 'Iraq' },
{ value: 'RU', label: 'Russia' },
{ value: 'UA', label: 'Ukraine' },
{ value: 'NG', label: 'Nigeria' },
{ value: 'CN', label: 'China' },
{ value: 'HU', label: 'Hungary' },
{ value: 'KE', label: 'Kenya' },
{ value: 'CO', label: 'Colombia' },
{ value: 'NZ', label: 'New Zealand' },
{ value: 'IR', label: 'Iran' },
{ value: 'CL', label: 'Chile' },
{ value: 'MD', label: 'Moldova' },
{ value: 'VN', label: 'Viet Nam' },
{ value: 'AS', label: 'American Samoa' },
{ value: 'HR', label: 'Croatia' },
{ value: 'IL', label: 'Israel' },
{ value: 'MT', label: 'Malta' },
]

export default jobLocation 